name = "MyJuliaRegistry"
uuid = "33688180-7f44-4de7-8754-061af9fbc328"
repo = "git@github.com:LexaLutyi/MyJuliaRegistry.git"
description = "My private registry"

[packages]
995f4f89-f633-4bea-be3c-9aca61510b0b = { name = "DataNetworkModels", path = "D/DataNetworkModels" }
