name = "MyJuliaRegistry"
uuid = "33688180-7f44-4de7-8754-061af9fbc328"
repo = "git@github.com:LexaLutyi/MyJuliaRegistry.git"
description = "My private registry"

[packages]
2adb0577-9a9d-4690-a5e9-28296fd30ae0 = { name = "BiologyNetworkModels", path = "B/BiologyNetworkModels" }
995f4f89-f633-4bea-be3c-9aca61510b0b = { name = "DataNetworkModels", path = "D/DataNetworkModels" }
