name = "MyJuliaRegistry"
uuid = "33688180-7f44-4de7-8754-061af9fbc328"
repo = "git@github.com:LexaLutyi/MyJuliaRegistry.git"
description = "My private registry"

[packages]
21bba74e-77d2-57ad-a443-e89d5f4545f6 = { name = "libcurl_jll", path = "jll/L/libcurl_jll" }
2adb0577-9a9d-4690-a5e9-28296fd30ae0 = { name = "BiologyNetworkModels", path = "B/BiologyNetworkModels" }
44bb7972-da25-4089-802e-d3afb760c9fe = { name = "TradeGame", path = "T/TradeGame" }
995f4f89-f633-4bea-be3c-9aca61510b0b = { name = "DataNetworkModels", path = "D/DataNetworkModels" }
a8bcf8b1-64b8-41f7-8d00-5e694f9aa795 = { name = "HttpClient", path = "H/HttpClient" }
a9341e5c-07f0-4893-8fea-80ee6f4ebcc7 = { name = "LibCURL2", path = "L/LibCURL2" }
b6b84edf-6aef-5ff6-9b66-656961a84a09 = { name = "libwebsockets_jll", path = "jll/L/libwebsockets_jll" }
c12848ba-5c2f-4249-8dfa-3c7bcec18efc = { name = "ImageReconstruction", path = "I/ImageReconstruction" }
d14b68a6-6005-4866-9a10-8ceb977a395a = { name = "DistributedControlSystems", path = "D/DistributedControlSystems" }
e0c91b13-f409-526f-9b5b-50444cc01a73 = { name = "LibCURL2_jll", path = "jll/L/LibCURL2_jll" }
f4bcb1d6-c0ed-4dc9-85bd-6dd0de3f2993 = { name = "EvolutionSimulation", path = "E/EvolutionSimulation" }
fcb5309f-8123-4a11-8e81-3d7aa8197287 = { name = "LibWebSockets", path = "L/LibWebSockets" }
